/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/section/Banner.vue')['default']
    BarChat: typeof import('./src/components/BarChat.vue')['default']
    GroupBarChat: typeof import('./src/components/GroupBarChat.vue')['default']
    InputList: typeof import('./src/components/InputList.vue')['default']
    LineChat: typeof import('./src/components/LineChat.vue')['default']
    Modal: typeof import('./src/components/common/Modal.vue')['default']
    MYFooter: typeof import('./src/components/layout/MYFooter.vue')['default']
    MyHeader: typeof import('./src/components/layout/MyHeader.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableChart: typeof import('./src/components/TableChart.vue')['default']
    TaiwanMap: typeof import('./src/components/TaiwanMap.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
  }
}
