/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/section/Banner.vue')['default']
    BarChat: typeof import('./src/components/BarChat.vue')['default']
    BarChat2: typeof import('./src/components/BarChat2.vue')['default']
    GroupBarChat: typeof import('./src/components/section/GroupBarChat.vue')['default']
    LineChat: typeof import('./src/components/LineChat.vue')['default']
    Modal: typeof import('./src/components/common/Modal.vue')['default']
    MyHeader: typeof import('./src/components/layout/MyHeader.vue')['default']
    NewTest: typeof import('./src/components/NewTest.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/Test.vue')['default']
  }
}
